version: '3.9'

services:
  web:
    build: .
    command: ./wait-for-db.sh python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Sang@123
      - DB_NAME=socialNetwork
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Sang@123
      MYSQL_DATABASE: socialNetwork
    ports:
      - "3306:3306"
